version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build: ./bot
    volumes:
      - ./bot:/app
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pgdata:
